#header nav
menu:
  home: /
  archives: archives
  categories: categories  
  tags: tags
  about: about

#site title
title: Synch

#your profile
profile: 
# put avatar in theme/source/img
  logo: Nayo
  avatar: /img/header.jpg
  author: Synch
  city: GuangZhou
  country: China
  descrption: If I walk would you run.If I stop would you come.

# put icon in theme/source/img
favicon: /img/favicon.png

#show/hide sidebar [true or false] 
sidebar: 
    false
  
# sidebar widgets
widgets:
- profile
- recent
- category
- tagcloud
- link

#recent_posts number
recent_posts:
  count: 6

#social link
social:  
  github: https://github.com/Lemonreds  
  zhihu:
  weibo:
  segmentfault: 
  facebook:
  twitter:
  instagram:
  linkedin:
  others:

#your friend link
link:
  ColorHexa: //www.colorhexa.com
  Google: //www.google.com
  Synch: //synch.site
# linkd: 
# linke:


# toc of post  [true or false]  
toc:
    true

# is fullscreen [ more width or less]
fullscreen:
    false

# only normal | todo
# code style
highlight_theme: 
    normal

# website analytics [your analytics id]
baidu_analytics:
  636802045446222199ae541e32c8133e
google_analytics: 