#header nav
menu:
  home: /
  archives: archives
  categories: categories  
  tags: tags
  about: about

#site title
title: Synch

#your profile
profile: 
# put avatar in theme/source/img
  logo: Nayo
  avatar: /img/header.png
  author: Synch
  city: GuangZhou
  country: China
  descrption: simple is simple,love is love

# put icon in theme/source/img
favicon: /img/favicon.png

#show/hide sidebar [true or false] 
sidebar: 
    true
  
# sidebar widgets
widgets:
- profile
- recent
- category
- tagcloud
- link

#recent_posts count
recent_posts:
  count: 8

#social link
social:  
  github: https://github.com/Lemonreds  
  zhihu:
  weibo:
  segmentfault: 
  facebook:
  twitter:
  instagram:
  linkedin:
  others:

#your friends link
link: 
  Google: //www.google.com  
  ColorHexa: //www.colorhexa.com 
  Synch: //synch.site
  Hexo: //https://hexo.io/
# linkd: 
# linke:


# toc of post  [true or false]  
toc:
    true

# is fullscreen [ more width or less]
fullscreen:
    false

# code style
# only normal | todo
highlight_theme: 
    normal

# website analytics [your analytics id]
baidu_analytics:
 636802045446222199ae541e32c8133e 
google_analytics: 

# busuanzi site count
busuanzi:
  true

# leancloud post count
leancloud:
  enable: true
  comment: true
  app_id: 
  app_key: 

#mob share
mob_share:
  enable: true
  app_key: 

#reward
reward:
  enable: false
  pic1: /img/r1.png
  pic2: /img/r2.png